# Numpy Exercises

In [7]:
# 1. Create a NumPy array containing the numbers from 1 to 10.
import numpy as np
ls = np.array([1,2,3,4,5,6,7,8,9,10])
ls
# :)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# 2. Extract the even numbers from the array created in Exercise 1.
list(filter(lambda x: x%2==0, ls))
# Is this valid? 
# :)

[2, 4, 6, 8, 10]

In [12]:
# Calculate the sum and mean of the array created in Exercise 1.
print(np.mean(ls))
print(np.sum(ls))
# :)


5.5
55


In [17]:
# 4. Create a 3x3 NumPy array with random integers between 1 and 9.
col1 = np.random.randint(1,9,3)
col2 = np.random.randint(1,9,3)
col3 = np.random.randint(1,9,3)
matriz = np.array([[col1,col2,col3]])
matriz
# less than 30 seconds :p :)

array([[[2, 7, 6],
        [6, 6, 5],
        [8, 3, 3]]])

In [20]:
# 5. Reshape the array from Exercise 4 into a 1D array.
m_1D = matriz.reshape(9,)
m_1D
# :D


array([2, 7, 6, 6, 6, 5, 8, 3, 3])

In [24]:
# 6. Concatenate two 1D NumPy arrays horizontally.
np.concatenate([m_1D,m_1D], axis=0)
# Is this correct? :)


array([2, 7, 6, 6, 6, 5, 8, 3, 3, 2, 7, 6, 6, 6, 5, 8, 3, 3])

In [41]:
# 7. Generate an array of 10 random numbers between 0 and 1 and filter out 
# values greater than 0.5.
arr = np.random.random(10)
list(filter(lambda x: x>0.5, arr))
# Perfect! I don't know if I'm answering in the right way,but im getting the things
# done, isn't it? :)

[0.8566810562096038,
 0.9032684830834687,
 0.6550138151598456,
 0.5724630197467789,
 0.604343205023468,
 0.6702879522577254,
 0.599998100120124]

In [43]:
# 8. Calculate the dot product of two 1D arrays of your choice.
arr1 = np.array([1,2,3])
arr2 = np.array([3,2,1])
print(arr1.shape, arr2.shape)


(3,) (3,)


In [49]:
np.dot(arr1,arr2)
# 1*3 + 2*2 + 3*1
# perfect! :)

10

In [55]:
# 9. Write a function to find the maximum and minimum values in a NumPy array.
def max_min(arr):
    max = np.max(arr)
    min = np.min(arr)
    return max, min
max_min(arr)
# :)



(0.9032684830834687, 0.13475241985077768)

In [56]:
# Create two NumPy arrays of different shapes and compare them element-wise 
# to find which elements are equal.
array1 = np.array([1, 2, 3, 4])
array2 = np.array([2, 2, 3, 4])

comparison_result = array1 == array2
print("Comparison Result:", comparison_result)
# didnt understand the exercise tbh u.u :(
# 9/10 It's okay n.n

Comparison Result: [False  True  True  True]
